[general]
import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[window]
padding = { x = 20, y = 20 }
decorations = "None"
opacity = 0.95
dynamic_padding = true
startup_mode = "Maximized"

[font]
normal = { family = "Lekton Nerd Font", style = "Regular" }
bold = { family = "Lekton Nerd Font", style = "Bold" }
italic = { family = "Lekton Nerd Font", style = "Italic" }
bold_italic = { family = "Lekton Nerd Font", style = "Bold Italic" }
size = 18

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0

